spring:
  application:
    name: springdataredis_demo

  redis:
    host: localhost
    port: 6379
    database: 0

    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
